DROP DATABASE IF EXISTS sodaPops_db;

CREATE DATABASE sodaPops_db;

USE sodaPops_db;

CREATE TABLE customers (
ID INTEGER (20) NOT NULL AUTO_INCREMENT,
name VARCHAR (30) NOT NULL,
email VARCHAR (50) NOT NULL,
phone INTEGER (10) NOT NULL,
comments INTEGER (30),
);

SELECT * FROM customers;
